/*
 * This file is generated by jOOQ.
*/
package com.ratpack.xin.db.tables.daos;


import com.ratpack.xin.db.tables.Articletype;
import com.ratpack.xin.db.tables.records.ArticletypeRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticletypeDao extends DAOImpl<ArticletypeRecord, com.ratpack.xin.db.tables.pojos.Articletype, Integer> {

    /**
     * Create a new ArticletypeDao without any configuration
     */
    public ArticletypeDao() {
        super(Articletype.ARTICLETYPE, com.ratpack.xin.db.tables.pojos.Articletype.class);
    }

    /**
     * Create a new ArticletypeDao with an attached configuration
     */
    public ArticletypeDao(Configuration configuration) {
        super(Articletype.ARTICLETYPE, com.ratpack.xin.db.tables.pojos.Articletype.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.ratpack.xin.db.tables.pojos.Articletype object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.ratpack.xin.db.tables.pojos.Articletype> fetchById(Integer... values) {
        return fetch(Articletype.ARTICLETYPE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.ratpack.xin.db.tables.pojos.Articletype fetchOneById(Integer value) {
        return fetchOne(Articletype.ARTICLETYPE.ID, value);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.ratpack.xin.db.tables.pojos.Articletype> fetchByCreateTime(Timestamp... values) {
        return fetch(Articletype.ARTICLETYPE.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>create_uuid IN (values)</code>
     */
    public List<com.ratpack.xin.db.tables.pojos.Articletype> fetchByCreateUuid(String... values) {
        return fetch(Articletype.ARTICLETYPE.CREATE_UUID, values);
    }

    /**
     * Fetch records that have <code>type_desc IN (values)</code>
     */
    public List<com.ratpack.xin.db.tables.pojos.Articletype> fetchByTypeDesc(String... values) {
        return fetch(Articletype.ARTICLETYPE.TYPE_DESC, values);
    }

    /**
     * Fetch records that have <code>create_user IN (values)</code>
     */
    public List<com.ratpack.xin.db.tables.pojos.Articletype> fetchByCreateUser(String... values) {
        return fetch(Articletype.ARTICLETYPE.CREATE_USER, values);
    }
}
