/*
 * This file is generated by jOOQ.
*/
package com.ratpack.xin.db.tables.daos;


import com.ratpack.xin.db.tables.Article;
import com.ratpack.xin.db.tables.records.ArticleRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleDao extends DAOImpl<ArticleRecord, com.ratpack.xin.db.tables.pojos.Article, Long> {

    /**
     * Create a new IArticleDao without any configuration
     */
    public ArticleDao() {
        super(Article.ARTICLE, com.ratpack.xin.db.tables.pojos.Article.class);
    }

    /**
     * Create a new IArticleDao with an attached configuration
     */
    public ArticleDao(Configuration configuration) {
        super(Article.ARTICLE, com.ratpack.xin.db.tables.pojos.Article.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.ratpack.xin.db.tables.pojos.Article object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.ratpack.xin.db.tables.pojos.Article> fetchById(Long... values) {
        return fetch(Article.ARTICLE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.ratpack.xin.db.tables.pojos.Article fetchOneById(Long value) {
        return fetchOne(Article.ARTICLE.ID, value);
    }

    /**
     * Fetch records that have <code>create_uuid IN (values)</code>
     */
    public List<com.ratpack.xin.db.tables.pojos.Article> fetchByCreateUuid(String... values) {
        return fetch(Article.ARTICLE.CREATE_UUID, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.ratpack.xin.db.tables.pojos.Article> fetchByCreateTime(Timestamp... values) {
        return fetch(Article.ARTICLE.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>blogauthor IN (values)</code>
     */
    public List<com.ratpack.xin.db.tables.pojos.Article> fetchByBlogauthor(String... values) {
        return fetch(Article.ARTICLE.BLOGAUTHOR, values);
    }

    /**
     * Fetch records that have <code>blogtype IN (values)</code>
     */
    public List<com.ratpack.xin.db.tables.pojos.Article> fetchByBlogtype(String... values) {
        return fetch(Article.ARTICLE.BLOGTYPE, values);
    }

    /**
     * Fetch records that have <code>blogtitie IN (values)</code>
     */
    public List<com.ratpack.xin.db.tables.pojos.Article> fetchByBlogtitie(String... values) {
        return fetch(Article.ARTICLE.BLOGTITIE, values);
    }

    /**
     * Fetch records that have <code>blogkeywords IN (values)</code>
     */
    public List<com.ratpack.xin.db.tables.pojos.Article> fetchByBlogkeywords(String... values) {
        return fetch(Article.ARTICLE.BLOGKEYWORDS, values);
    }

    /**
     * Fetch records that have <code>blogabstract IN (values)</code>
     */
    public List<com.ratpack.xin.db.tables.pojos.Article> fetchByBlogabstract(String... values) {
        return fetch(Article.ARTICLE.BLOGABSTRACT, values);
    }

    /**
     * Fetch records that have <code>blogcontent IN (values)</code>
     */
    public List<com.ratpack.xin.db.tables.pojos.Article> fetchByBlogcontent(String... values) {
        return fetch(Article.ARTICLE.BLOGCONTENT, values);
    }
}
