/*
 * This file is generated by jOOQ.
*/
package com.ratpack.xin.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Article implements Serializable {

    private static final long serialVersionUID = -75700150;

    private Long      id;
    private String    createUuid;
    private Timestamp createTime;
    private String    blogauthor;
    private String    blogtype;
    private String    blogtitie;
    private String    blogkeywords;
    private String    blogabstract;
    private String    blogcontent;

    public Article() {}

    public Article(Article value) {
        this.id = value.id;
        this.createUuid = value.createUuid;
        this.createTime = value.createTime;
        this.blogauthor = value.blogauthor;
        this.blogtype = value.blogtype;
        this.blogtitie = value.blogtitie;
        this.blogkeywords = value.blogkeywords;
        this.blogabstract = value.blogabstract;
        this.blogcontent = value.blogcontent;
    }

    public Article(
        Long      id,
        String    createUuid,
        Timestamp createTime,
        String    blogauthor,
        String    blogtype,
        String    blogtitie,
        String    blogkeywords,
        String    blogabstract,
        String    blogcontent
    ) {
        this.id = id;
        this.createUuid = createUuid;
        this.createTime = createTime;
        this.blogauthor = blogauthor;
        this.blogtype = blogtype;
        this.blogtitie = blogtitie;
        this.blogkeywords = blogkeywords;
        this.blogabstract = blogabstract;
        this.blogcontent = blogcontent;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCreateUuid() {
        return this.createUuid;
    }

    public void setCreateUuid(String createUuid) {
        this.createUuid = createUuid;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public String getBlogauthor() {
        return this.blogauthor;
    }

    public void setBlogauthor(String blogauthor) {
        this.blogauthor = blogauthor;
    }

    public String getBlogtype() {
        return this.blogtype;
    }

    public void setBlogtype(String blogtype) {
        this.blogtype = blogtype;
    }

    public String getBlogtitie() {
        return this.blogtitie;
    }

    public void setBlogtitie(String blogtitie) {
        this.blogtitie = blogtitie;
    }

    public String getBlogkeywords() {
        return this.blogkeywords;
    }

    public void setBlogkeywords(String blogkeywords) {
        this.blogkeywords = blogkeywords;
    }

    public String getBlogabstract() {
        return this.blogabstract;
    }

    public void setBlogabstract(String blogabstract) {
        this.blogabstract = blogabstract;
    }

    public String getBlogcontent() {
        return this.blogcontent;
    }

    public void setBlogcontent(String blogcontent) {
        this.blogcontent = blogcontent;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Article (");

        sb.append(id);
        sb.append(", ").append(createUuid);
        sb.append(", ").append(createTime);
        sb.append(", ").append(blogauthor);
        sb.append(", ").append(blogtype);
        sb.append(", ").append(blogtitie);
        sb.append(", ").append(blogkeywords);
        sb.append(", ").append(blogabstract);
        sb.append(", ").append(blogcontent);

        sb.append(")");
        return sb.toString();
    }
}
