/*
 * This file is generated by jOOQ.
*/
package com.ratpack.xin.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Articletype implements Serializable {

    private static final long serialVersionUID = -2102076349;

    private Integer   id;
    private Timestamp createTime;
    private String    createUuid;
    private String    typeDesc;
    private String    createUser;

    public Articletype() {}

    public Articletype(Articletype value) {
        this.id = value.id;
        this.createTime = value.createTime;
        this.createUuid = value.createUuid;
        this.typeDesc = value.typeDesc;
        this.createUser = value.createUser;
    }

    public Articletype(
        Integer   id,
        Timestamp createTime,
        String    createUuid,
        String    typeDesc,
        String    createUser
    ) {
        this.id = id;
        this.createTime = createTime;
        this.createUuid = createUuid;
        this.typeDesc = typeDesc;
        this.createUser = createUser;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public String getCreateUuid() {
        return this.createUuid;
    }

    public void setCreateUuid(String createUuid) {
        this.createUuid = createUuid;
    }

    public String getTypeDesc() {
        return this.typeDesc;
    }

    public void setTypeDesc(String typeDesc) {
        this.typeDesc = typeDesc;
    }

    public String getCreateUser() {
        return this.createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Articletype (");

        sb.append(id);
        sb.append(", ").append(createTime);
        sb.append(", ").append(createUuid);
        sb.append(", ").append(typeDesc);
        sb.append(", ").append(createUser);

        sb.append(")");
        return sb.toString();
    }
}
