/*
 * This file is generated by jOOQ.
*/
package com.ratpack.xin.db;


import com.ratpack.xin.db.tables.Article;
import com.ratpack.xin.db.tables.Articletype;
import com.ratpack.xin.db.tables.Userinfo;
import com.ratpack.xin.db.tables.records.ArticleRecord;
import com.ratpack.xin.db.tables.records.ArticletypeRecord;
import com.ratpack.xin.db.tables.records.UserinfoRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>ratpack</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ArticleRecord, Long> IDENTITY_ARTICLE = Identities0.IDENTITY_ARTICLE;
    public static final Identity<ArticletypeRecord, Integer> IDENTITY_ARTICLETYPE = Identities0.IDENTITY_ARTICLETYPE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ArticleRecord> KEY_ARTICLE_PRIMARY = UniqueKeys0.KEY_ARTICLE_PRIMARY;
    public static final UniqueKey<ArticletypeRecord> KEY_ARTICLETYPE_PRIMARY = UniqueKeys0.KEY_ARTICLETYPE_PRIMARY;
    public static final UniqueKey<UserinfoRecord> KEY_USERINFO_PRIMARY = UniqueKeys0.KEY_USERINFO_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<ArticleRecord, Long> IDENTITY_ARTICLE = createIdentity(Article.ARTICLE, Article.ARTICLE.ID);
        public static Identity<ArticletypeRecord, Integer> IDENTITY_ARTICLETYPE = createIdentity(Articletype.ARTICLETYPE, Articletype.ARTICLETYPE.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ArticleRecord> KEY_ARTICLE_PRIMARY = createUniqueKey(Article.ARTICLE, "KEY_article_PRIMARY", Article.ARTICLE.ID);
        public static final UniqueKey<ArticletypeRecord> KEY_ARTICLETYPE_PRIMARY = createUniqueKey(Articletype.ARTICLETYPE, "KEY_articletype_PRIMARY", Articletype.ARTICLETYPE.ID);
        public static final UniqueKey<UserinfoRecord> KEY_USERINFO_PRIMARY = createUniqueKey(Userinfo.USERINFO, "KEY_userinfo_PRIMARY", Userinfo.USERINFO.USERID);
    }
}
