/*
 * This file is generated by jOOQ.
*/
package com.ratpack.xin.db;


import com.ratpack.xin.db.tables.Article;
import com.ratpack.xin.db.tables.Articletype;
import com.ratpack.xin.db.tables.Userinfo;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ratpack extends SchemaImpl {

    private static final long serialVersionUID = 693477735;

    /**
     * The reference instance of <code>ratpack</code>
     */
    public static final Ratpack RATPACK = new Ratpack();

    /**
     * The table <code>ratpack.article</code>.
     */
    public final Article ARTICLE = com.ratpack.xin.db.tables.Article.ARTICLE;

    /**
     * The table <code>ratpack.articletype</code>.
     */
    public final Articletype ARTICLETYPE = com.ratpack.xin.db.tables.Articletype.ARTICLETYPE;

    /**
     * The table <code>ratpack.userinfo</code>.
     */
    public final Userinfo USERINFO = com.ratpack.xin.db.tables.Userinfo.USERINFO;

    /**
     * No further instances allowed
     */
    private Ratpack() {
        super("ratpack", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Article.ARTICLE,
            Articletype.ARTICLETYPE,
            Userinfo.USERINFO);
    }
}
