/*
 * This file is generated by jOOQ.
*/
package com.ratpack.xin.db;


import com.ratpack.xin.db.tables.Article;
import com.ratpack.xin.db.tables.Userinfo;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in ratpack
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ratpack.article</code>.
     */
    public static final Article ARTICLE = com.ratpack.xin.db.tables.Article.ARTICLE;

    /**
     * The table <code>ratpack.userinfo</code>.
     */
    public static final Userinfo USERINFO = com.ratpack.xin.db.tables.Userinfo.USERINFO;
}
