/*
 * This file is generated by jOOQ.
*/
package com.ratpack.xin.db.tables;


import com.ratpack.xin.db.Keys;
import com.ratpack.xin.db.Ratpack;
import com.ratpack.xin.db.tables.records.UserinfoRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Userinfo extends TableImpl<UserinfoRecord> {

    private static final long serialVersionUID = -895981418;

    /**
     * The reference instance of <code>ratpack.userinfo</code>
     */
    public static final Userinfo USERINFO = new Userinfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserinfoRecord> getRecordType() {
        return UserinfoRecord.class;
    }

    /**
     * The column <code>ratpack.userinfo.userid</code>. 用户id
     */
    public final TableField<UserinfoRecord, String> USERID = createField("userid", org.jooq.impl.SQLDataType.VARCHAR.length(22).nullable(false), this, "用户id");

    /**
     * The column <code>ratpack.userinfo.username</code>.
     */
    public final TableField<UserinfoRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(22), this, "");

    /**
     * The column <code>ratpack.userinfo.userpassword</code>.
     */
    public final TableField<UserinfoRecord, String> USERPASSWORD = createField("userpassword", org.jooq.impl.SQLDataType.VARCHAR.length(22), this, "");

    /**
     * The column <code>ratpack.userinfo.userphone</code>.
     */
    public final TableField<UserinfoRecord, String> USERPHONE = createField("userphone", org.jooq.impl.SQLDataType.VARCHAR.length(22), this, "");

    /**
     * The column <code>ratpack.userinfo.usersex</code>. 性别
     */
    public final TableField<UserinfoRecord, String> USERSEX = createField("usersex", org.jooq.impl.SQLDataType.VARCHAR.length(2), this, "性别");

    /**
     * The column <code>ratpack.userinfo.usercountry</code>.
     */
    public final TableField<UserinfoRecord, String> USERCOUNTRY = createField("usercountry", org.jooq.impl.SQLDataType.VARCHAR.length(22), this, "");

    /**
     * The column <code>ratpack.userinfo.userprovince</code>.
     */
    public final TableField<UserinfoRecord, String> USERPROVINCE = createField("userprovince", org.jooq.impl.SQLDataType.VARCHAR.length(22), this, "");

    /**
     * The column <code>ratpack.userinfo.usercity</code>.
     */
    public final TableField<UserinfoRecord, String> USERCITY = createField("usercity", org.jooq.impl.SQLDataType.VARCHAR.length(22), this, "");

    /**
     * The column <code>ratpack.userinfo.userarea</code>.
     */
    public final TableField<UserinfoRecord, String> USERAREA = createField("userarea", org.jooq.impl.SQLDataType.VARCHAR.length(22), this, "");

    /**
     * The column <code>ratpack.userinfo.usercreatetime</code>.
     */
    public final TableField<UserinfoRecord, String> USERCREATETIME = createField("usercreatetime", org.jooq.impl.SQLDataType.VARCHAR.length(22), this, "");

    /**
     * The column <code>ratpack.userinfo.userhead</code>. 头像
     */
    public final TableField<UserinfoRecord, String> USERHEAD = createField("userhead", org.jooq.impl.SQLDataType.VARCHAR.length(22), this, "头像");

    /**
     * The column <code>ratpack.userinfo.qqid</code>. 绑定qq登陆
     */
    public final TableField<UserinfoRecord, String> QQID = createField("qqid", org.jooq.impl.SQLDataType.VARCHAR.length(22), this, "绑定qq登陆");

    /**
     * The column <code>ratpack.userinfo.wxid</code>. 绑定微信
     */
    public final TableField<UserinfoRecord, String> WXID = createField("wxid", org.jooq.impl.SQLDataType.VARCHAR.length(22), this, "绑定微信");

    /**
     * Create a <code>ratpack.userinfo</code> table reference
     */
    public Userinfo() {
        this("userinfo", null);
    }

    /**
     * Create an aliased <code>ratpack.userinfo</code> table reference
     */
    public Userinfo(String alias) {
        this(alias, USERINFO);
    }

    private Userinfo(String alias, Table<UserinfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private Userinfo(String alias, Table<UserinfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ratpack.RATPACK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserinfoRecord> getPrimaryKey() {
        return Keys.KEY_USERINFO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserinfoRecord>> getKeys() {
        return Arrays.<UniqueKey<UserinfoRecord>>asList(Keys.KEY_USERINFO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Userinfo as(String alias) {
        return new Userinfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Userinfo rename(String name) {
        return new Userinfo(name, null);
    }
}
