// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: info_common.proto

package com.ratpack.xin.pojo;

public final class InfoCommon {
  private InfoCommon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ratpack.xin.pojo.UserInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用户ID
     * </pre>
     *
     * <code>required string userid = 1;</code>
     */
    boolean hasUserid();
    /**
     * <pre>
     *用户ID
     * </pre>
     *
     * <code>required string userid = 1;</code>
     */
    java.lang.String getUserid();
    /**
     * <pre>
     *用户ID
     * </pre>
     *
     * <code>required string userid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUseridBytes();

    /**
     * <pre>
     *用户名字
     * </pre>
     *
     * <code>optional string username = 2;</code>
     */
    boolean hasUsername();
    /**
     * <pre>
     *用户名字
     * </pre>
     *
     * <code>optional string username = 2;</code>
     */
    java.lang.String getUsername();
    /**
     * <pre>
     *用户名字
     * </pre>
     *
     * <code>optional string username = 2;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <pre>
     *用户密码
     * </pre>
     *
     * <code>optional string userpassword = 3;</code>
     */
    boolean hasUserpassword();
    /**
     * <pre>
     *用户密码
     * </pre>
     *
     * <code>optional string userpassword = 3;</code>
     */
    java.lang.String getUserpassword();
    /**
     * <pre>
     *用户密码
     * </pre>
     *
     * <code>optional string userpassword = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserpasswordBytes();

    /**
     * <pre>
     *手机号码
     * </pre>
     *
     * <code>optional string userphone = 4;</code>
     */
    boolean hasUserphone();
    /**
     * <pre>
     *手机号码
     * </pre>
     *
     * <code>optional string userphone = 4;</code>
     */
    java.lang.String getUserphone();
    /**
     * <pre>
     *手机号码
     * </pre>
     *
     * <code>optional string userphone = 4;</code>
     */
    com.google.protobuf.ByteString
        getUserphoneBytes();

    /**
     * <pre>
     *性别
     * </pre>
     *
     * <code>optional string usersex = 5;</code>
     */
    boolean hasUsersex();
    /**
     * <pre>
     *性别
     * </pre>
     *
     * <code>optional string usersex = 5;</code>
     */
    java.lang.String getUsersex();
    /**
     * <pre>
     *性别
     * </pre>
     *
     * <code>optional string usersex = 5;</code>
     */
    com.google.protobuf.ByteString
        getUsersexBytes();

    /**
     * <pre>
     *国家
     * </pre>
     *
     * <code>optional string usercountry = 6;</code>
     */
    boolean hasUsercountry();
    /**
     * <pre>
     *国家
     * </pre>
     *
     * <code>optional string usercountry = 6;</code>
     */
    java.lang.String getUsercountry();
    /**
     * <pre>
     *国家
     * </pre>
     *
     * <code>optional string usercountry = 6;</code>
     */
    com.google.protobuf.ByteString
        getUsercountryBytes();

    /**
     * <pre>
     *省
     * </pre>
     *
     * <code>optional string userprovince = 7;</code>
     */
    boolean hasUserprovince();
    /**
     * <pre>
     *省
     * </pre>
     *
     * <code>optional string userprovince = 7;</code>
     */
    java.lang.String getUserprovince();
    /**
     * <pre>
     *省
     * </pre>
     *
     * <code>optional string userprovince = 7;</code>
     */
    com.google.protobuf.ByteString
        getUserprovinceBytes();

    /**
     * <pre>
     *市
     * </pre>
     *
     * <code>optional string usercity = 8;</code>
     */
    boolean hasUsercity();
    /**
     * <pre>
     *市
     * </pre>
     *
     * <code>optional string usercity = 8;</code>
     */
    java.lang.String getUsercity();
    /**
     * <pre>
     *市
     * </pre>
     *
     * <code>optional string usercity = 8;</code>
     */
    com.google.protobuf.ByteString
        getUsercityBytes();

    /**
     * <pre>
     *区
     * </pre>
     *
     * <code>optional string userarea = 9;</code>
     */
    boolean hasUserarea();
    /**
     * <pre>
     *区
     * </pre>
     *
     * <code>optional string userarea = 9;</code>
     */
    java.lang.String getUserarea();
    /**
     * <pre>
     *区
     * </pre>
     *
     * <code>optional string userarea = 9;</code>
     */
    com.google.protobuf.ByteString
        getUserareaBytes();

    /**
     * <pre>
     *注册时间
     * </pre>
     *
     * <code>optional string usercreatetime = 10;</code>
     */
    boolean hasUsercreatetime();
    /**
     * <pre>
     *注册时间
     * </pre>
     *
     * <code>optional string usercreatetime = 10;</code>
     */
    java.lang.String getUsercreatetime();
    /**
     * <pre>
     *注册时间
     * </pre>
     *
     * <code>optional string usercreatetime = 10;</code>
     */
    com.google.protobuf.ByteString
        getUsercreatetimeBytes();

    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>optional string userhead = 11;</code>
     */
    boolean hasUserhead();
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>optional string userhead = 11;</code>
     */
    java.lang.String getUserhead();
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>optional string userhead = 11;</code>
     */
    com.google.protobuf.ByteString
        getUserheadBytes();

    /**
     * <pre>
     *绑定qq登陆
     * </pre>
     *
     * <code>optional string qqid = 12;</code>
     */
    boolean hasQqid();
    /**
     * <pre>
     *绑定qq登陆
     * </pre>
     *
     * <code>optional string qqid = 12;</code>
     */
    java.lang.String getQqid();
    /**
     * <pre>
     *绑定qq登陆
     * </pre>
     *
     * <code>optional string qqid = 12;</code>
     */
    com.google.protobuf.ByteString
        getQqidBytes();

    /**
     * <pre>
     *绑定微信
     * </pre>
     *
     * <code>optional string wxid = 13;</code>
     */
    boolean hasWxid();
    /**
     * <pre>
     *绑定微信
     * </pre>
     *
     * <code>optional string wxid = 13;</code>
     */
    java.lang.String getWxid();
    /**
     * <pre>
     *绑定微信
     * </pre>
     *
     * <code>optional string wxid = 13;</code>
     */
    com.google.protobuf.ByteString
        getWxidBytes();
  }
  /**
   * <pre>
   *用户信息
   * </pre>
   *
   * Protobuf type {@code com.ratpack.xin.pojo.UserInfo}
   */
  public  static final class UserInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ratpack.xin.pojo.UserInfo)
      UserInfoOrBuilder {
    // Use UserInfo.newBuilder() to construct.
    private UserInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserInfo() {
      userid_ = "";
      username_ = "";
      userpassword_ = "";
      userphone_ = "";
      usersex_ = "";
      usercountry_ = "";
      userprovince_ = "";
      usercity_ = "";
      userarea_ = "";
      usercreatetime_ = "";
      userhead_ = "";
      qqid_ = "";
      wxid_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              userid_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              username_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              userpassword_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              userphone_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              usersex_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              usercountry_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              userprovince_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              usercity_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              userarea_ = bs;
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              usercreatetime_ = bs;
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              userhead_ = bs;
              break;
            }
            case 98: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000800;
              qqid_ = bs;
              break;
            }
            case 106: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00001000;
              wxid_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ratpack.xin.pojo.InfoCommon.internal_static_com_ratpack_xin_pojo_UserInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ratpack.xin.pojo.InfoCommon.internal_static_com_ratpack_xin_pojo_UserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ratpack.xin.pojo.InfoCommon.UserInfo.class, com.ratpack.xin.pojo.InfoCommon.UserInfo.Builder.class);
    }

    private int bitField0_;
    public static final int USERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object userid_;
    /**
     * <pre>
     *用户ID
     * </pre>
     *
     * <code>required string userid = 1;</code>
     */
    public boolean hasUserid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *用户ID
     * </pre>
     *
     * <code>required string userid = 1;</code>
     */
    public java.lang.String getUserid() {
      java.lang.Object ref = userid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userid_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *用户ID
     * </pre>
     *
     * <code>required string userid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUseridBytes() {
      java.lang.Object ref = userid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object username_;
    /**
     * <pre>
     *用户名字
     * </pre>
     *
     * <code>optional string username = 2;</code>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *用户名字
     * </pre>
     *
     * <code>optional string username = 2;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *用户名字
     * </pre>
     *
     * <code>optional string username = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERPASSWORD_FIELD_NUMBER = 3;
    private volatile java.lang.Object userpassword_;
    /**
     * <pre>
     *用户密码
     * </pre>
     *
     * <code>optional string userpassword = 3;</code>
     */
    public boolean hasUserpassword() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *用户密码
     * </pre>
     *
     * <code>optional string userpassword = 3;</code>
     */
    public java.lang.String getUserpassword() {
      java.lang.Object ref = userpassword_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userpassword_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *用户密码
     * </pre>
     *
     * <code>optional string userpassword = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserpasswordBytes() {
      java.lang.Object ref = userpassword_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userpassword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERPHONE_FIELD_NUMBER = 4;
    private volatile java.lang.Object userphone_;
    /**
     * <pre>
     *手机号码
     * </pre>
     *
     * <code>optional string userphone = 4;</code>
     */
    public boolean hasUserphone() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *手机号码
     * </pre>
     *
     * <code>optional string userphone = 4;</code>
     */
    public java.lang.String getUserphone() {
      java.lang.Object ref = userphone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userphone_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *手机号码
     * </pre>
     *
     * <code>optional string userphone = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUserphoneBytes() {
      java.lang.Object ref = userphone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userphone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERSEX_FIELD_NUMBER = 5;
    private volatile java.lang.Object usersex_;
    /**
     * <pre>
     *性别
     * </pre>
     *
     * <code>optional string usersex = 5;</code>
     */
    public boolean hasUsersex() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     *性别
     * </pre>
     *
     * <code>optional string usersex = 5;</code>
     */
    public java.lang.String getUsersex() {
      java.lang.Object ref = usersex_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          usersex_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *性别
     * </pre>
     *
     * <code>optional string usersex = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUsersexBytes() {
      java.lang.Object ref = usersex_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        usersex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERCOUNTRY_FIELD_NUMBER = 6;
    private volatile java.lang.Object usercountry_;
    /**
     * <pre>
     *国家
     * </pre>
     *
     * <code>optional string usercountry = 6;</code>
     */
    public boolean hasUsercountry() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     *国家
     * </pre>
     *
     * <code>optional string usercountry = 6;</code>
     */
    public java.lang.String getUsercountry() {
      java.lang.Object ref = usercountry_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          usercountry_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *国家
     * </pre>
     *
     * <code>optional string usercountry = 6;</code>
     */
    public com.google.protobuf.ByteString
        getUsercountryBytes() {
      java.lang.Object ref = usercountry_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        usercountry_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERPROVINCE_FIELD_NUMBER = 7;
    private volatile java.lang.Object userprovince_;
    /**
     * <pre>
     *省
     * </pre>
     *
     * <code>optional string userprovince = 7;</code>
     */
    public boolean hasUserprovince() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     *省
     * </pre>
     *
     * <code>optional string userprovince = 7;</code>
     */
    public java.lang.String getUserprovince() {
      java.lang.Object ref = userprovince_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userprovince_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *省
     * </pre>
     *
     * <code>optional string userprovince = 7;</code>
     */
    public com.google.protobuf.ByteString
        getUserprovinceBytes() {
      java.lang.Object ref = userprovince_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userprovince_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERCITY_FIELD_NUMBER = 8;
    private volatile java.lang.Object usercity_;
    /**
     * <pre>
     *市
     * </pre>
     *
     * <code>optional string usercity = 8;</code>
     */
    public boolean hasUsercity() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <pre>
     *市
     * </pre>
     *
     * <code>optional string usercity = 8;</code>
     */
    public java.lang.String getUsercity() {
      java.lang.Object ref = usercity_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          usercity_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *市
     * </pre>
     *
     * <code>optional string usercity = 8;</code>
     */
    public com.google.protobuf.ByteString
        getUsercityBytes() {
      java.lang.Object ref = usercity_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        usercity_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERAREA_FIELD_NUMBER = 9;
    private volatile java.lang.Object userarea_;
    /**
     * <pre>
     *区
     * </pre>
     *
     * <code>optional string userarea = 9;</code>
     */
    public boolean hasUserarea() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <pre>
     *区
     * </pre>
     *
     * <code>optional string userarea = 9;</code>
     */
    public java.lang.String getUserarea() {
      java.lang.Object ref = userarea_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userarea_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *区
     * </pre>
     *
     * <code>optional string userarea = 9;</code>
     */
    public com.google.protobuf.ByteString
        getUserareaBytes() {
      java.lang.Object ref = userarea_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userarea_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERCREATETIME_FIELD_NUMBER = 10;
    private volatile java.lang.Object usercreatetime_;
    /**
     * <pre>
     *注册时间
     * </pre>
     *
     * <code>optional string usercreatetime = 10;</code>
     */
    public boolean hasUsercreatetime() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <pre>
     *注册时间
     * </pre>
     *
     * <code>optional string usercreatetime = 10;</code>
     */
    public java.lang.String getUsercreatetime() {
      java.lang.Object ref = usercreatetime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          usercreatetime_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *注册时间
     * </pre>
     *
     * <code>optional string usercreatetime = 10;</code>
     */
    public com.google.protobuf.ByteString
        getUsercreatetimeBytes() {
      java.lang.Object ref = usercreatetime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        usercreatetime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERHEAD_FIELD_NUMBER = 11;
    private volatile java.lang.Object userhead_;
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>optional string userhead = 11;</code>
     */
    public boolean hasUserhead() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>optional string userhead = 11;</code>
     */
    public java.lang.String getUserhead() {
      java.lang.Object ref = userhead_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userhead_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>optional string userhead = 11;</code>
     */
    public com.google.protobuf.ByteString
        getUserheadBytes() {
      java.lang.Object ref = userhead_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userhead_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QQID_FIELD_NUMBER = 12;
    private volatile java.lang.Object qqid_;
    /**
     * <pre>
     *绑定qq登陆
     * </pre>
     *
     * <code>optional string qqid = 12;</code>
     */
    public boolean hasQqid() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <pre>
     *绑定qq登陆
     * </pre>
     *
     * <code>optional string qqid = 12;</code>
     */
    public java.lang.String getQqid() {
      java.lang.Object ref = qqid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          qqid_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *绑定qq登陆
     * </pre>
     *
     * <code>optional string qqid = 12;</code>
     */
    public com.google.protobuf.ByteString
        getQqidBytes() {
      java.lang.Object ref = qqid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        qqid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WXID_FIELD_NUMBER = 13;
    private volatile java.lang.Object wxid_;
    /**
     * <pre>
     *绑定微信
     * </pre>
     *
     * <code>optional string wxid = 13;</code>
     */
    public boolean hasWxid() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <pre>
     *绑定微信
     * </pre>
     *
     * <code>optional string wxid = 13;</code>
     */
    public java.lang.String getWxid() {
      java.lang.Object ref = wxid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          wxid_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *绑定微信
     * </pre>
     *
     * <code>optional string wxid = 13;</code>
     */
    public com.google.protobuf.ByteString
        getWxidBytes() {
      java.lang.Object ref = wxid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wxid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) {
        return true;
      }
      if (isInitialized == 0) return false;

      if (!hasUserid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, username_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userpassword_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userphone_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, usersex_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, usercountry_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, userprovince_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, usercity_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, userarea_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, usercreatetime_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, userhead_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, qqid_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, wxid_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, username_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userpassword_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userphone_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, usersex_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, usercountry_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, userprovince_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, usercity_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, userarea_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, usercreatetime_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, userhead_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, qqid_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, wxid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ratpack.xin.pojo.InfoCommon.UserInfo)) {
        return super.equals(obj);
      }
      com.ratpack.xin.pojo.InfoCommon.UserInfo other = (com.ratpack.xin.pojo.InfoCommon.UserInfo) obj;

      boolean result = true;
      result = result && (hasUserid() == other.hasUserid());
      if (hasUserid()) {
        result = result && getUserid()
            .equals(other.getUserid());
      }
      result = result && (hasUsername() == other.hasUsername());
      if (hasUsername()) {
        result = result && getUsername()
            .equals(other.getUsername());
      }
      result = result && (hasUserpassword() == other.hasUserpassword());
      if (hasUserpassword()) {
        result = result && getUserpassword()
            .equals(other.getUserpassword());
      }
      result = result && (hasUserphone() == other.hasUserphone());
      if (hasUserphone()) {
        result = result && getUserphone()
            .equals(other.getUserphone());
      }
      result = result && (hasUsersex() == other.hasUsersex());
      if (hasUsersex()) {
        result = result && getUsersex()
            .equals(other.getUsersex());
      }
      result = result && (hasUsercountry() == other.hasUsercountry());
      if (hasUsercountry()) {
        result = result && getUsercountry()
            .equals(other.getUsercountry());
      }
      result = result && (hasUserprovince() == other.hasUserprovince());
      if (hasUserprovince()) {
        result = result && getUserprovince()
            .equals(other.getUserprovince());
      }
      result = result && (hasUsercity() == other.hasUsercity());
      if (hasUsercity()) {
        result = result && getUsercity()
            .equals(other.getUsercity());
      }
      result = result && (hasUserarea() == other.hasUserarea());
      if (hasUserarea()) {
        result = result && getUserarea()
            .equals(other.getUserarea());
      }
      result = result && (hasUsercreatetime() == other.hasUsercreatetime());
      if (hasUsercreatetime()) {
        result = result && getUsercreatetime()
            .equals(other.getUsercreatetime());
      }
      result = result && (hasUserhead() == other.hasUserhead());
      if (hasUserhead()) {
        result = result && getUserhead()
            .equals(other.getUserhead());
      }
      result = result && (hasQqid() == other.hasQqid());
      if (hasQqid()) {
        result = result && getQqid()
            .equals(other.getQqid());
      }
      result = result && (hasWxid() == other.hasWxid());
      if (hasWxid()) {
        result = result && getWxid()
            .equals(other.getWxid());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasUserid()) {
        hash = (37 * hash) + USERID_FIELD_NUMBER;
        hash = (53 * hash) + getUserid().hashCode();
      }
      if (hasUsername()) {
        hash = (37 * hash) + USERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getUsername().hashCode();
      }
      if (hasUserpassword()) {
        hash = (37 * hash) + USERPASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getUserpassword().hashCode();
      }
      if (hasUserphone()) {
        hash = (37 * hash) + USERPHONE_FIELD_NUMBER;
        hash = (53 * hash) + getUserphone().hashCode();
      }
      if (hasUsersex()) {
        hash = (37 * hash) + USERSEX_FIELD_NUMBER;
        hash = (53 * hash) + getUsersex().hashCode();
      }
      if (hasUsercountry()) {
        hash = (37 * hash) + USERCOUNTRY_FIELD_NUMBER;
        hash = (53 * hash) + getUsercountry().hashCode();
      }
      if (hasUserprovince()) {
        hash = (37 * hash) + USERPROVINCE_FIELD_NUMBER;
        hash = (53 * hash) + getUserprovince().hashCode();
      }
      if (hasUsercity()) {
        hash = (37 * hash) + USERCITY_FIELD_NUMBER;
        hash = (53 * hash) + getUsercity().hashCode();
      }
      if (hasUserarea()) {
        hash = (37 * hash) + USERAREA_FIELD_NUMBER;
        hash = (53 * hash) + getUserarea().hashCode();
      }
      if (hasUsercreatetime()) {
        hash = (37 * hash) + USERCREATETIME_FIELD_NUMBER;
        hash = (53 * hash) + getUsercreatetime().hashCode();
      }
      if (hasUserhead()) {
        hash = (37 * hash) + USERHEAD_FIELD_NUMBER;
        hash = (53 * hash) + getUserhead().hashCode();
      }
      if (hasQqid()) {
        hash = (37 * hash) + QQID_FIELD_NUMBER;
        hash = (53 * hash) + getQqid().hashCode();
      }
      if (hasWxid()) {
        hash = (37 * hash) + WXID_FIELD_NUMBER;
        hash = (53 * hash) + getWxid().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ratpack.xin.pojo.InfoCommon.UserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ratpack.xin.pojo.InfoCommon.UserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ratpack.xin.pojo.InfoCommon.UserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ratpack.xin.pojo.InfoCommon.UserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ratpack.xin.pojo.InfoCommon.UserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ratpack.xin.pojo.InfoCommon.UserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ratpack.xin.pojo.InfoCommon.UserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ratpack.xin.pojo.InfoCommon.UserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ratpack.xin.pojo.InfoCommon.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ratpack.xin.pojo.InfoCommon.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ratpack.xin.pojo.InfoCommon.UserInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *用户信息
     * </pre>
     *
     * Protobuf type {@code com.ratpack.xin.pojo.UserInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ratpack.xin.pojo.UserInfo)
        com.ratpack.xin.pojo.InfoCommon.UserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ratpack.xin.pojo.InfoCommon.internal_static_com_ratpack_xin_pojo_UserInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ratpack.xin.pojo.InfoCommon.internal_static_com_ratpack_xin_pojo_UserInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ratpack.xin.pojo.InfoCommon.UserInfo.class, com.ratpack.xin.pojo.InfoCommon.UserInfo.Builder.class);
      }

      // Construct using com.ratpack.xin.pojo.InfoCommon.UserInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        userpassword_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        userphone_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        usersex_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        usercountry_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        userprovince_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        usercity_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        userarea_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        usercreatetime_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        userhead_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        qqid_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        wxid_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ratpack.xin.pojo.InfoCommon.internal_static_com_ratpack_xin_pojo_UserInfo_descriptor;
      }

      public com.ratpack.xin.pojo.InfoCommon.UserInfo getDefaultInstanceForType() {
        return com.ratpack.xin.pojo.InfoCommon.UserInfo.getDefaultInstance();
      }

      public com.ratpack.xin.pojo.InfoCommon.UserInfo build() {
        com.ratpack.xin.pojo.InfoCommon.UserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ratpack.xin.pojo.InfoCommon.UserInfo buildPartial() {
        com.ratpack.xin.pojo.InfoCommon.UserInfo result = new com.ratpack.xin.pojo.InfoCommon.UserInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userid_ = userid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userpassword_ = userpassword_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.userphone_ = userphone_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.usersex_ = usersex_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.usercountry_ = usercountry_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.userprovince_ = userprovince_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.usercity_ = usercity_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.userarea_ = userarea_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.usercreatetime_ = usercreatetime_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.userhead_ = userhead_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.qqid_ = qqid_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.wxid_ = wxid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ratpack.xin.pojo.InfoCommon.UserInfo) {
          return mergeFrom((com.ratpack.xin.pojo.InfoCommon.UserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ratpack.xin.pojo.InfoCommon.UserInfo other) {
        if (other == com.ratpack.xin.pojo.InfoCommon.UserInfo.getDefaultInstance()) return this;
        if (other.hasUserid()) {
          bitField0_ |= 0x00000001;
          userid_ = other.userid_;
          onChanged();
        }
        if (other.hasUsername()) {
          bitField0_ |= 0x00000002;
          username_ = other.username_;
          onChanged();
        }
        if (other.hasUserpassword()) {
          bitField0_ |= 0x00000004;
          userpassword_ = other.userpassword_;
          onChanged();
        }
        if (other.hasUserphone()) {
          bitField0_ |= 0x00000008;
          userphone_ = other.userphone_;
          onChanged();
        }
        if (other.hasUsersex()) {
          bitField0_ |= 0x00000010;
          usersex_ = other.usersex_;
          onChanged();
        }
        if (other.hasUsercountry()) {
          bitField0_ |= 0x00000020;
          usercountry_ = other.usercountry_;
          onChanged();
        }
        if (other.hasUserprovince()) {
          bitField0_ |= 0x00000040;
          userprovince_ = other.userprovince_;
          onChanged();
        }
        if (other.hasUsercity()) {
          bitField0_ |= 0x00000080;
          usercity_ = other.usercity_;
          onChanged();
        }
        if (other.hasUserarea()) {
          bitField0_ |= 0x00000100;
          userarea_ = other.userarea_;
          onChanged();
        }
        if (other.hasUsercreatetime()) {
          bitField0_ |= 0x00000200;
          usercreatetime_ = other.usercreatetime_;
          onChanged();
        }
        if (other.hasUserhead()) {
          bitField0_ |= 0x00000400;
          userhead_ = other.userhead_;
          onChanged();
        }
        if (other.hasQqid()) {
          bitField0_ |= 0x00000800;
          qqid_ = other.qqid_;
          onChanged();
        }
        if (other.hasWxid()) {
          bitField0_ |= 0x00001000;
          wxid_ = other.wxid_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserid()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ratpack.xin.pojo.InfoCommon.UserInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ratpack.xin.pojo.InfoCommon.UserInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object userid_ = "";
      /**
       * <pre>
       *用户ID
       * </pre>
       *
       * <code>required string userid = 1;</code>
       */
      public boolean hasUserid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *用户ID
       * </pre>
       *
       * <code>required string userid = 1;</code>
       */
      public java.lang.String getUserid() {
        java.lang.Object ref = userid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户ID
       * </pre>
       *
       * <code>required string userid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUseridBytes() {
        java.lang.Object ref = userid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户ID
       * </pre>
       *
       * <code>required string userid = 1;</code>
       */
      public Builder setUserid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户ID
       * </pre>
       *
       * <code>required string userid = 1;</code>
       */
      public Builder clearUserid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userid_ = getDefaultInstance().getUserid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户ID
       * </pre>
       *
       * <code>required string userid = 1;</code>
       */
      public Builder setUseridBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object username_ = "";
      /**
       * <pre>
       *用户名字
       * </pre>
       *
       * <code>optional string username = 2;</code>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *用户名字
       * </pre>
       *
       * <code>optional string username = 2;</code>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            username_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户名字
       * </pre>
       *
       * <code>optional string username = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户名字
       * </pre>
       *
       * <code>optional string username = 2;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户名字
       * </pre>
       *
       * <code>optional string username = 2;</code>
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000002);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户名字
       * </pre>
       *
       * <code>optional string username = 2;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        username_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userpassword_ = "";
      /**
       * <pre>
       *用户密码
       * </pre>
       *
       * <code>optional string userpassword = 3;</code>
       */
      public boolean hasUserpassword() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *用户密码
       * </pre>
       *
       * <code>optional string userpassword = 3;</code>
       */
      public java.lang.String getUserpassword() {
        java.lang.Object ref = userpassword_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userpassword_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户密码
       * </pre>
       *
       * <code>optional string userpassword = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserpasswordBytes() {
        java.lang.Object ref = userpassword_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userpassword_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户密码
       * </pre>
       *
       * <code>optional string userpassword = 3;</code>
       */
      public Builder setUserpassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userpassword_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户密码
       * </pre>
       *
       * <code>optional string userpassword = 3;</code>
       */
      public Builder clearUserpassword() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userpassword_ = getDefaultInstance().getUserpassword();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户密码
       * </pre>
       *
       * <code>optional string userpassword = 3;</code>
       */
      public Builder setUserpasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userpassword_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userphone_ = "";
      /**
       * <pre>
       *手机号码
       * </pre>
       *
       * <code>optional string userphone = 4;</code>
       */
      public boolean hasUserphone() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       *手机号码
       * </pre>
       *
       * <code>optional string userphone = 4;</code>
       */
      public java.lang.String getUserphone() {
        java.lang.Object ref = userphone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userphone_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *手机号码
       * </pre>
       *
       * <code>optional string userphone = 4;</code>
       */
      public com.google.protobuf.ByteString
          getUserphoneBytes() {
        java.lang.Object ref = userphone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userphone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *手机号码
       * </pre>
       *
       * <code>optional string userphone = 4;</code>
       */
      public Builder setUserphone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        userphone_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *手机号码
       * </pre>
       *
       * <code>optional string userphone = 4;</code>
       */
      public Builder clearUserphone() {
        bitField0_ = (bitField0_ & ~0x00000008);
        userphone_ = getDefaultInstance().getUserphone();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *手机号码
       * </pre>
       *
       * <code>optional string userphone = 4;</code>
       */
      public Builder setUserphoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        userphone_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object usersex_ = "";
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>optional string usersex = 5;</code>
       */
      public boolean hasUsersex() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>optional string usersex = 5;</code>
       */
      public java.lang.String getUsersex() {
        java.lang.Object ref = usersex_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            usersex_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>optional string usersex = 5;</code>
       */
      public com.google.protobuf.ByteString
          getUsersexBytes() {
        java.lang.Object ref = usersex_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          usersex_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>optional string usersex = 5;</code>
       */
      public Builder setUsersex(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        usersex_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>optional string usersex = 5;</code>
       */
      public Builder clearUsersex() {
        bitField0_ = (bitField0_ & ~0x00000010);
        usersex_ = getDefaultInstance().getUsersex();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>optional string usersex = 5;</code>
       */
      public Builder setUsersexBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        usersex_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object usercountry_ = "";
      /**
       * <pre>
       *国家
       * </pre>
       *
       * <code>optional string usercountry = 6;</code>
       */
      public boolean hasUsercountry() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <pre>
       *国家
       * </pre>
       *
       * <code>optional string usercountry = 6;</code>
       */
      public java.lang.String getUsercountry() {
        java.lang.Object ref = usercountry_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            usercountry_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *国家
       * </pre>
       *
       * <code>optional string usercountry = 6;</code>
       */
      public com.google.protobuf.ByteString
          getUsercountryBytes() {
        java.lang.Object ref = usercountry_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          usercountry_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *国家
       * </pre>
       *
       * <code>optional string usercountry = 6;</code>
       */
      public Builder setUsercountry(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        usercountry_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *国家
       * </pre>
       *
       * <code>optional string usercountry = 6;</code>
       */
      public Builder clearUsercountry() {
        bitField0_ = (bitField0_ & ~0x00000020);
        usercountry_ = getDefaultInstance().getUsercountry();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *国家
       * </pre>
       *
       * <code>optional string usercountry = 6;</code>
       */
      public Builder setUsercountryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        usercountry_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userprovince_ = "";
      /**
       * <pre>
       *省
       * </pre>
       *
       * <code>optional string userprovince = 7;</code>
       */
      public boolean hasUserprovince() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <pre>
       *省
       * </pre>
       *
       * <code>optional string userprovince = 7;</code>
       */
      public java.lang.String getUserprovince() {
        java.lang.Object ref = userprovince_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userprovince_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *省
       * </pre>
       *
       * <code>optional string userprovince = 7;</code>
       */
      public com.google.protobuf.ByteString
          getUserprovinceBytes() {
        java.lang.Object ref = userprovince_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userprovince_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *省
       * </pre>
       *
       * <code>optional string userprovince = 7;</code>
       */
      public Builder setUserprovince(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        userprovince_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *省
       * </pre>
       *
       * <code>optional string userprovince = 7;</code>
       */
      public Builder clearUserprovince() {
        bitField0_ = (bitField0_ & ~0x00000040);
        userprovince_ = getDefaultInstance().getUserprovince();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *省
       * </pre>
       *
       * <code>optional string userprovince = 7;</code>
       */
      public Builder setUserprovinceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        userprovince_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object usercity_ = "";
      /**
       * <pre>
       *市
       * </pre>
       *
       * <code>optional string usercity = 8;</code>
       */
      public boolean hasUsercity() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <pre>
       *市
       * </pre>
       *
       * <code>optional string usercity = 8;</code>
       */
      public java.lang.String getUsercity() {
        java.lang.Object ref = usercity_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            usercity_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *市
       * </pre>
       *
       * <code>optional string usercity = 8;</code>
       */
      public com.google.protobuf.ByteString
          getUsercityBytes() {
        java.lang.Object ref = usercity_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          usercity_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *市
       * </pre>
       *
       * <code>optional string usercity = 8;</code>
       */
      public Builder setUsercity(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        usercity_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *市
       * </pre>
       *
       * <code>optional string usercity = 8;</code>
       */
      public Builder clearUsercity() {
        bitField0_ = (bitField0_ & ~0x00000080);
        usercity_ = getDefaultInstance().getUsercity();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *市
       * </pre>
       *
       * <code>optional string usercity = 8;</code>
       */
      public Builder setUsercityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        usercity_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userarea_ = "";
      /**
       * <pre>
       *区
       * </pre>
       *
       * <code>optional string userarea = 9;</code>
       */
      public boolean hasUserarea() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <pre>
       *区
       * </pre>
       *
       * <code>optional string userarea = 9;</code>
       */
      public java.lang.String getUserarea() {
        java.lang.Object ref = userarea_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userarea_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *区
       * </pre>
       *
       * <code>optional string userarea = 9;</code>
       */
      public com.google.protobuf.ByteString
          getUserareaBytes() {
        java.lang.Object ref = userarea_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userarea_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *区
       * </pre>
       *
       * <code>optional string userarea = 9;</code>
       */
      public Builder setUserarea(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        userarea_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *区
       * </pre>
       *
       * <code>optional string userarea = 9;</code>
       */
      public Builder clearUserarea() {
        bitField0_ = (bitField0_ & ~0x00000100);
        userarea_ = getDefaultInstance().getUserarea();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *区
       * </pre>
       *
       * <code>optional string userarea = 9;</code>
       */
      public Builder setUserareaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        userarea_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object usercreatetime_ = "";
      /**
       * <pre>
       *注册时间
       * </pre>
       *
       * <code>optional string usercreatetime = 10;</code>
       */
      public boolean hasUsercreatetime() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <pre>
       *注册时间
       * </pre>
       *
       * <code>optional string usercreatetime = 10;</code>
       */
      public java.lang.String getUsercreatetime() {
        java.lang.Object ref = usercreatetime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            usercreatetime_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *注册时间
       * </pre>
       *
       * <code>optional string usercreatetime = 10;</code>
       */
      public com.google.protobuf.ByteString
          getUsercreatetimeBytes() {
        java.lang.Object ref = usercreatetime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          usercreatetime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *注册时间
       * </pre>
       *
       * <code>optional string usercreatetime = 10;</code>
       */
      public Builder setUsercreatetime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        usercreatetime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *注册时间
       * </pre>
       *
       * <code>optional string usercreatetime = 10;</code>
       */
      public Builder clearUsercreatetime() {
        bitField0_ = (bitField0_ & ~0x00000200);
        usercreatetime_ = getDefaultInstance().getUsercreatetime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *注册时间
       * </pre>
       *
       * <code>optional string usercreatetime = 10;</code>
       */
      public Builder setUsercreatetimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        usercreatetime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userhead_ = "";
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>optional string userhead = 11;</code>
       */
      public boolean hasUserhead() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>optional string userhead = 11;</code>
       */
      public java.lang.String getUserhead() {
        java.lang.Object ref = userhead_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userhead_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>optional string userhead = 11;</code>
       */
      public com.google.protobuf.ByteString
          getUserheadBytes() {
        java.lang.Object ref = userhead_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userhead_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>optional string userhead = 11;</code>
       */
      public Builder setUserhead(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        userhead_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>optional string userhead = 11;</code>
       */
      public Builder clearUserhead() {
        bitField0_ = (bitField0_ & ~0x00000400);
        userhead_ = getDefaultInstance().getUserhead();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>optional string userhead = 11;</code>
       */
      public Builder setUserheadBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        userhead_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object qqid_ = "";
      /**
       * <pre>
       *绑定qq登陆
       * </pre>
       *
       * <code>optional string qqid = 12;</code>
       */
      public boolean hasQqid() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <pre>
       *绑定qq登陆
       * </pre>
       *
       * <code>optional string qqid = 12;</code>
       */
      public java.lang.String getQqid() {
        java.lang.Object ref = qqid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            qqid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *绑定qq登陆
       * </pre>
       *
       * <code>optional string qqid = 12;</code>
       */
      public com.google.protobuf.ByteString
          getQqidBytes() {
        java.lang.Object ref = qqid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          qqid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *绑定qq登陆
       * </pre>
       *
       * <code>optional string qqid = 12;</code>
       */
      public Builder setQqid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        qqid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *绑定qq登陆
       * </pre>
       *
       * <code>optional string qqid = 12;</code>
       */
      public Builder clearQqid() {
        bitField0_ = (bitField0_ & ~0x00000800);
        qqid_ = getDefaultInstance().getQqid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *绑定qq登陆
       * </pre>
       *
       * <code>optional string qqid = 12;</code>
       */
      public Builder setQqidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        qqid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object wxid_ = "";
      /**
       * <pre>
       *绑定微信
       * </pre>
       *
       * <code>optional string wxid = 13;</code>
       */
      public boolean hasWxid() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <pre>
       *绑定微信
       * </pre>
       *
       * <code>optional string wxid = 13;</code>
       */
      public java.lang.String getWxid() {
        java.lang.Object ref = wxid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            wxid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *绑定微信
       * </pre>
       *
       * <code>optional string wxid = 13;</code>
       */
      public com.google.protobuf.ByteString
          getWxidBytes() {
        java.lang.Object ref = wxid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          wxid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *绑定微信
       * </pre>
       *
       * <code>optional string wxid = 13;</code>
       */
      public Builder setWxid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        wxid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *绑定微信
       * </pre>
       *
       * <code>optional string wxid = 13;</code>
       */
      public Builder clearWxid() {
        bitField0_ = (bitField0_ & ~0x00001000);
        wxid_ = getDefaultInstance().getWxid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *绑定微信
       * </pre>
       *
       * <code>optional string wxid = 13;</code>
       */
      public Builder setWxidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        wxid_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ratpack.xin.pojo.UserInfo)
    }

    // @@protoc_insertion_point(class_scope:com.ratpack.xin.pojo.UserInfo)
    private static final com.ratpack.xin.pojo.InfoCommon.UserInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ratpack.xin.pojo.InfoCommon.UserInfo();
    }

    public static com.ratpack.xin.pojo.InfoCommon.UserInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<UserInfo>
        PARSER = new com.google.protobuf.AbstractParser<UserInfo>() {
      public UserInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UserInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserInfo> getParserForType() {
      return PARSER;
    }

    public com.ratpack.xin.pojo.InfoCommon.UserInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ratpack_xin_pojo_UserInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ratpack_xin_pojo_UserInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021info_common.proto\022\024com.ratpack.xin.poj" +
      "o\"\373\001\n\010UserInfo\022\016\n\006userid\030\001 \002(\t\022\020\n\010userna" +
      "me\030\002 \001(\t\022\024\n\014userpassword\030\003 \001(\t\022\021\n\tuserph" +
      "one\030\004 \001(\t\022\017\n\007usersex\030\005 \001(\t\022\023\n\013usercountr" +
      "y\030\006 \001(\t\022\024\n\014userprovince\030\007 \001(\t\022\020\n\010usercit" +
      "y\030\010 \001(\t\022\020\n\010userarea\030\t \001(\t\022\026\n\016usercreatet" +
      "ime\030\n \001(\t\022\020\n\010userhead\030\013 \001(\t\022\014\n\004qqid\030\014 \001(" +
      "\t\022\014\n\004wxid\030\r \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ratpack_xin_pojo_UserInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ratpack_xin_pojo_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ratpack_xin_pojo_UserInfo_descriptor,
        new java.lang.String[] { "Userid", "Username", "Userpassword", "Userphone", "Usersex", "Usercountry", "Userprovince", "Usercity", "Userarea", "Usercreatetime", "Userhead", "Qqid", "Wxid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
