/*
 * This file is generated by jOOQ.
*/
package com.ratpack.xin.db.tables.records;


import com.ratpack.xin.db.tables.Articletype;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticletypeRecord extends UpdatableRecordImpl<ArticletypeRecord> implements Record5<Integer, Timestamp, String, String, String> {

    private static final long serialVersionUID = -1230846554;

    /**
     * Setter for <code>ratpack.articletype.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ratpack.articletype.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ratpack.articletype.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>ratpack.articletype.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>ratpack.articletype.create_uuid</code>.
     */
    public void setCreateUuid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ratpack.articletype.create_uuid</code>.
     */
    public String getCreateUuid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ratpack.articletype.type_desc</code>.
     */
    public void setTypeDesc(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ratpack.articletype.type_desc</code>.
     */
    public String getTypeDesc() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ratpack.articletype.create_user</code>.
     */
    public void setCreateUser(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>ratpack.articletype.create_user</code>.
     */
    public String getCreateUser() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Timestamp, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Timestamp, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Articletype.ARTICLETYPE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Articletype.ARTICLETYPE.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Articletype.ARTICLETYPE.CREATE_UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Articletype.ARTICLETYPE.TYPE_DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Articletype.ARTICLETYPE.CREATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCreateUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTypeDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticletypeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticletypeRecord value2(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticletypeRecord value3(String value) {
        setCreateUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticletypeRecord value4(String value) {
        setTypeDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticletypeRecord value5(String value) {
        setCreateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticletypeRecord values(Integer value1, Timestamp value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArticletypeRecord
     */
    public ArticletypeRecord() {
        super(Articletype.ARTICLETYPE);
    }

    /**
     * Create a detached, initialised ArticletypeRecord
     */
    public ArticletypeRecord(Integer id, Timestamp createTime, String createUuid, String typeDesc, String createUser) {
        super(Articletype.ARTICLETYPE);

        set(0, id);
        set(1, createTime);
        set(2, createUuid);
        set(3, typeDesc);
        set(4, createUser);
    }
}
