/*
 * This file is generated by jOOQ.
*/
package com.ratpack.xin.db.tables.records;


import com.ratpack.xin.db.tables.Userinfo;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserinfoRecord extends UpdatableRecordImpl<UserinfoRecord> implements Record13<String, String, String, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -1272500574;

    /**
     * Setter for <code>ratpack.userinfo.userid</code>. 用户id
     */
    public void setUserid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>ratpack.userinfo.userid</code>. 用户id
     */
    public String getUserid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ratpack.userinfo.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ratpack.userinfo.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ratpack.userinfo.userpassword</code>.
     */
    public void setUserpassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ratpack.userinfo.userpassword</code>.
     */
    public String getUserpassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ratpack.userinfo.userphone</code>.
     */
    public void setUserphone(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ratpack.userinfo.userphone</code>.
     */
    public String getUserphone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ratpack.userinfo.usersex</code>. 性别
     */
    public void setUsersex(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>ratpack.userinfo.usersex</code>. 性别
     */
    public String getUsersex() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ratpack.userinfo.usercountry</code>.
     */
    public void setUsercountry(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>ratpack.userinfo.usercountry</code>.
     */
    public String getUsercountry() {
        return (String) get(5);
    }

    /**
     * Setter for <code>ratpack.userinfo.userprovince</code>.
     */
    public void setUserprovince(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>ratpack.userinfo.userprovince</code>.
     */
    public String getUserprovince() {
        return (String) get(6);
    }

    /**
     * Setter for <code>ratpack.userinfo.usercity</code>.
     */
    public void setUsercity(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>ratpack.userinfo.usercity</code>.
     */
    public String getUsercity() {
        return (String) get(7);
    }

    /**
     * Setter for <code>ratpack.userinfo.userarea</code>.
     */
    public void setUserarea(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>ratpack.userinfo.userarea</code>.
     */
    public String getUserarea() {
        return (String) get(8);
    }

    /**
     * Setter for <code>ratpack.userinfo.usercreatetime</code>.
     */
    public void setUsercreatetime(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>ratpack.userinfo.usercreatetime</code>.
     */
    public String getUsercreatetime() {
        return (String) get(9);
    }

    /**
     * Setter for <code>ratpack.userinfo.userhead</code>. 头像
     */
    public void setUserhead(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>ratpack.userinfo.userhead</code>. 头像
     */
    public String getUserhead() {
        return (String) get(10);
    }

    /**
     * Setter for <code>ratpack.userinfo.qqid</code>. 绑定qq登陆
     */
    public void setQqid(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>ratpack.userinfo.qqid</code>. 绑定qq登陆
     */
    public String getQqid() {
        return (String) get(11);
    }

    /**
     * Setter for <code>ratpack.userinfo.wxid</code>. 绑定微信
     */
    public void setWxid(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>ratpack.userinfo.wxid</code>. 绑定微信
     */
    public String getWxid() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<String, String, String, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<String, String, String, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Userinfo.USERINFO.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Userinfo.USERINFO.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Userinfo.USERINFO.USERPASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Userinfo.USERINFO.USERPHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Userinfo.USERINFO.USERSEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Userinfo.USERINFO.USERCOUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Userinfo.USERINFO.USERPROVINCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Userinfo.USERINFO.USERCITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Userinfo.USERINFO.USERAREA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Userinfo.USERINFO.USERCREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Userinfo.USERINFO.USERHEAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Userinfo.USERINFO.QQID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Userinfo.USERINFO.WXID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUserpassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUserphone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUsersex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUsercountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getUserprovince();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getUsercity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getUserarea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getUsercreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getUserhead();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getQqid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getWxid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserinfoRecord value1(String value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserinfoRecord value2(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserinfoRecord value3(String value) {
        setUserpassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserinfoRecord value4(String value) {
        setUserphone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserinfoRecord value5(String value) {
        setUsersex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserinfoRecord value6(String value) {
        setUsercountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserinfoRecord value7(String value) {
        setUserprovince(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserinfoRecord value8(String value) {
        setUsercity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserinfoRecord value9(String value) {
        setUserarea(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserinfoRecord value10(String value) {
        setUsercreatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserinfoRecord value11(String value) {
        setUserhead(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserinfoRecord value12(String value) {
        setQqid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserinfoRecord value13(String value) {
        setWxid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserinfoRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserinfoRecord
     */
    public UserinfoRecord() {
        super(Userinfo.USERINFO);
    }

    /**
     * Create a detached, initialised UserinfoRecord
     */
    public UserinfoRecord(String userid, String username, String userpassword, String userphone, String usersex, String usercountry, String userprovince, String usercity, String userarea, String usercreatetime, String userhead, String qqid, String wxid) {
        super(Userinfo.USERINFO);

        set(0, userid);
        set(1, username);
        set(2, userpassword);
        set(3, userphone);
        set(4, usersex);
        set(5, usercountry);
        set(6, userprovince);
        set(7, usercity);
        set(8, userarea);
        set(9, usercreatetime);
        set(10, userhead);
        set(11, qqid);
        set(12, wxid);
    }
}
